spring:
  application:
    name: user

server:
  port: 8447
  
say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8780,localhost:8781,localhost:8782
    ServerListRefreshInterval: 15000